name: chronos
services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data # Crucial for persisting SSL certificates
      - caddy_config:/config
    environment:
      CLIENT_URL: ${CLIENT_URL}
      CLIENT_PORT: ${CLIENT_PORT}

      ADMIN_URL: ${ADMIN_URL}
      ADMIN_PORT: ${ADMIN_PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
    depends_on:
      - client
      - admin

  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: chronos/client
    environment:
      NODE_ENV: production
      PORT: "3000"

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    restart: always

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: chronos/admin
    environment:
      NODE_ENV: production
      PORT: "3001"

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    restart: always

volumes:
  data:
  caddy_data:
  caddy_config:
