name: chronos
services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    image: chronos/client
    environment:
      NODE_ENV: production
      PORT: "3000"

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    image: chronos/admin
    environment:
      NODE_ENV: production
      PORT: "3001"

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  data:
