import type { Metadata } from "next";
import "@chronos/ui/globals.css";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="fr">
      <body className="antialiased">{children}</body>
    </html>
  );
}
